# Generated by Django 4.1.5 on 2023-05-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_images_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='Images',
            field=models.ImageField(upload_to='app/static/assets/images'),
        ),
    ]
