# Generated by Django 4.1.5 on 2023-05-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_images_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Palnts',
        ),
    ]
